<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/L2.GameContent/L2.GameContent.csproj" />
    <ProjectReference Include="../../src/L2.GameServer/L2.GameServer.csproj" />
    <ProjectReference Include="../../src/L2.LoginServer/L2.LoginServer.csproj" />
    <ProjectReference Include="../../src/L2.PlayerCharacters/L2.PlayerCharacters.csproj" />
    <ProjectReference Include="../../src/L2.PlayerIdentity/L2.PlayerIdentity.csproj" />
  </ItemGroup>
</Project>
