<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../L2.Server.Contracts/L2.Server.Contracts.csproj" />
    <ProjectReference Include="../L2.Server.Repositories.Interfaces/L2.Server.Repositories.Interfaces.csproj" />
    <ProjectReference Include="../L2.Server.Services.Interfaces/L2.Server.Services.Interfaces.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
</Project>
