// <auto-generated />
using System;
using L2.PlayerCharacters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace L2.PlayerCharacters.Migrations
{
    [DbContext(typeof(PlayerCharactersDbContext))]
    [Migration("20260809182724_InitialPlayerCharacters")]
    partial class InitialPlayerCharacters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("player")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("L2.PlayerCharacters.Entities.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("AccountSlot")
                        .HasColumnType("integer")
                        .HasColumnName("account_slot");

                    b.Property<int>("ActiveClassId")
                        .HasColumnType("integer")
                        .HasColumnName("active_class_id");

                    b.Property<int>("BaseClassId")
                        .HasColumnType("integer")
                        .HasColumnName("base_class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeleteAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_after");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("experience");

                    b.Property<int>("FaceId")
                        .HasColumnType("integer")
                        .HasColumnName("face_id");

                    b.Property<int>("HairColorId")
                        .HasColumnType("integer")
                        .HasColumnName("hair_color_id");

                    b.Property<int>("HairStyleId")
                        .HasColumnType("integer")
                        .HasColumnName("hair_style_id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeleteAfter")
                        .HasDatabaseName("ix_characters_deletion_deadline")
                        .HasFilter("delete_after IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_normalized_name");

                    b.HasIndex("AccountId", "AccountSlot")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_account_slot");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_characters_account_created");

                    b.ToTable("characters", "player", t =>
                        {
                            t.HasCheckConstraint("ck_characters_account_slot", "account_slot >= 0");

                            t.HasCheckConstraint("ck_characters_experience", "experience >= 0");

                            t.HasCheckConstraint("ck_characters_level", "level BETWEEN 1 AND 255");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
