// <auto-generated />
using System;
using L2.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace L2.Server.Migrations
{
    [DbContext(typeof(L2ServerDbContext))]
    [Migration("20260812022518_AddGameServersAndGlobalLogin")]
    partial class AddGameServersAndGlobalLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("L2.Server.Context.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_normalized_username");

                    b.ToTable("accounts", "public");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.AccountCredential", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId");

                    b.ToTable("account_credentials", "public");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.AccountLoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("failure_code");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_account_login_history_account_time");

                    b.ToTable("account_login_history", "public");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.AccountSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_sessions_token_hash");

                    b.HasIndex("AccountId", "ExpiresAt")
                        .HasDatabaseName("ix_account_sessions_account_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("account_sessions", "public");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_hash");

                    b.Property<Guid>("AccountSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GameServer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_server");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_version");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("SelectedCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_character_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_game_sessions_access_token_hash");

                    b.HasIndex("AccountSessionId")
                        .HasDatabaseName("ix_game_sessions_account_session_id");

                    b.HasIndex("GameVersion");

                    b.HasIndex("RevokedAt", "ExpiresAt")
                        .HasDatabaseName("ix_game_sessions_active_expiry");

                    b.ToTable("game_sessions", "public");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.GameSessionTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_session_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GameServer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_server");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_version");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AccountSessionId")
                        .HasDatabaseName("ix_game_session_tickets_account_session_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_game_session_tickets_pending_expiry")
                        .HasFilter("consumed_at IS NULL");

                    b.HasIndex("GameVersion");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_game_session_tickets_token_hash");

                    b.ToTable("game_session_tickets", "public");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.GameVersion", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_game_versions_display_name");

                    b.ToTable("game_versions", "public");

                    b.HasData(
                        new
                        {
                            Key = "c1",
                            DisplayName = "Chronicle 1",
                            SortOrder = 10
                        },
                        new
                        {
                            Key = "c4",
                            DisplayName = "Chronicle 4",
                            SortOrder = 20
                        },
                        new
                        {
                            Key = "interlude",
                            DisplayName = "Interlude",
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("L2.Server.Context.Entities.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("AccountSlot")
                        .HasColumnType("integer")
                        .HasColumnName("account_slot");

                    b.Property<int>("ActiveClassId")
                        .HasColumnType("integer")
                        .HasColumnName("active_class_id");

                    b.Property<int>("BaseClassId")
                        .HasColumnType("integer")
                        .HasColumnName("base_class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeleteAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_after");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("experience");

                    b.Property<int>("FaceId")
                        .HasColumnType("integer")
                        .HasColumnName("face_id");

                    b.Property<string>("GameServer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_server");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_version");

                    b.Property<int>("HairColorId")
                        .HasColumnType("integer")
                        .HasColumnName("hair_color_id");

                    b.Property<int>("HairStyleId")
                        .HasColumnType("integer")
                        .HasColumnName("hair_style_id");

                    b.Property<bool>("IsMage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mage");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeleteAfter")
                        .HasDatabaseName("ix_characters_deletion_deadline")
                        .HasFilter("delete_after IS NOT NULL");

                    b.HasIndex("GameVersion", "GameServer", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_normalized_name");

                    b.HasIndex("GameVersion", "GameServer", "AccountId", "AccountSlot")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_account_slot");

                    b.HasIndex("GameVersion", "GameServer", "AccountId", "CreatedAt")
                        .HasDatabaseName("ix_characters_account_created");

                    b.ToTable("characters", "public", t =>
                        {
                            t.HasCheckConstraint("ck_characters_account_slot", "account_slot >= 0");

                            t.HasCheckConstraint("ck_characters_experience", "experience >= 0");

                            t.HasCheckConstraint("ck_characters_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Server.Context.Entities.AccountCredential", b =>
                {
                    b.HasOne("L2.Server.Context.Entities.Account", "Account")
                        .WithOne("Credential")
                        .HasForeignKey("L2.Server.Context.Entities.AccountCredential", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.AccountLoginHistory", b =>
                {
                    b.HasOne("L2.Server.Context.Entities.Account", "Account")
                        .WithMany("LoginHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.AccountSession", b =>
                {
                    b.HasOne("L2.Server.Context.Entities.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.GameSession", b =>
                {
                    b.HasOne("L2.Server.Context.Entities.AccountSession", "AccountSession")
                        .WithMany("GameSessions")
                        .HasForeignKey("AccountSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Server.Context.Entities.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountSession");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.GameSessionTicket", b =>
                {
                    b.HasOne("L2.Server.Context.Entities.AccountSession", "AccountSession")
                        .WithMany("GameTickets")
                        .HasForeignKey("AccountSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Server.Context.Entities.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountSession");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.PlayerCharacter", b =>
                {
                    b.HasOne("L2.Server.Context.Entities.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.Account", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("LoginHistory");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("L2.Server.Context.Entities.AccountSession", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("GameTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
